// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.StrongHold2016.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc692.StrongHold2016.Robot;
import org.usfirst.frc692.StrongHold2016.subsystems.Gatherer;

/**
 *
 */
public class GathererArmOperator extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public GathererArmOperator() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.gatherer);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Gatherer.armPosition = Gatherer.ArmPositions.Neutral;
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double yAxis = Robot.oi.operatorJoystick.getY();
    	double speed = yAxis;
    	double denominator = 0;
    	SmartDashboard.putString("OperatorJoystickArmGatherer", Double.toString(yAxis));
    	if(Robot.gatherer.getLimitSwitchDown().get()){
    		SmartDashboard.putString("LimitSwtichDown", "True");
    	}
    	else{
    		SmartDashboard.putString("LimitSwtichDown", "False");
    	}
    	if(Robot.gatherer.getLimitSwitchUp().get()){
    		SmartDashboard.putString("LimitSwtichUp", "True");
    	}
    	else{
    		SmartDashboard.putString("LimitSwtichUp", "False");
    	}
    	
    	if (yAxis < 0){
    		if(Robot.gatherer.getLimitSwitchDown().get()){
    			return;
    		}

    		denominator = (double) -1.5;
    			 
    		 
    		// if Joystick value is greater than zero it will make the max speed 50%
    		// will check if limit switch is pressed, if not it will return to check again
    		// AO 2/21/16
    		 
    	}else{
    		if(Robot.gatherer.getLimitSwitchUp().get()){
    			return;
    		}

    		denominator = (double) -2.0;
    		
    		// if Joystick value is less than zero it will make max speed 50%
    		// will check if limit switch is pressed, if not it will return to check again
    		// AO 2/21/16
    	}

		speed = yAxis / denominator;
		SmartDashboard.putString("OperatorJoystickArmGathererSpeed", Double.toString(speed));
		
	 	Robot.gatherer.setGathererArmLiftMotor(speed);
	 	// if no limit switch is pressed, this method will continue the motor to continue moving
	 	// AO 2/21/16
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
// Jesus will guide you to write this code 
